# Generated by Django 2.0.1 on 2018-02-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('type', models.CharField(default='unknown', max_length=20)),
                ('registrationNumber', models.CharField(default='unknown', max_length=10, primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('name', models.CharField(default='unknown', max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(default='unknown', max_length=20)),
                ('timeZone', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('number', models.CharField(default='unknown', max_length=6, primary_key=True, serialize=False)),
                ('numberOfSeats', models.IntegerField(default=0)),
                ('status', models.CharField(default='unknown', max_length=9)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='unknown', max_length=6)),
                ('departureTime', models.DateTimeField(null=True)),
                ('arrivalTime', models.DateTimeField(null=True)),
                ('duration', models.DurationField()),
                ('price', models.FloatField(default=0)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Aircraft')),
                ('departureAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airline.Airport')),
                ('destinationAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='airline.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('airlineReferenceNumber', models.CharField(default='unknown', max_length=10, primary_key=True, serialize=False)),
                ('paymentProviderReferenceNumber', models.CharField(default='unknown', max_length=10)),
                ('amount', models.FloatField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='unknown', max_length=30)),
                ('surname', models.CharField(default='unknown', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(default='unknown', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('address', models.URLField()),
                ('accountNumber', models.CharField(default='unknown', max_length=30)),
                ('login', models.CharField(default='unknown', max_length=20)),
                ('password', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='airline.Passenger'),
        ),
    ]
