# Generated by Django 2.0.1 on 2018-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stamp',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='airlineReferenceNumber',
            field=models.CharField(default='unknown', max_length=6, primary_key=True, serialize=False),
        ),
    ]
