# Generated by Django 2.0.2 on 2018-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20180226_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stamp',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
