# Generated by Django 2.0.1 on 2018-03-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_auto_20180226_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.Flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='airline.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departureAirport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure', to='airline.Airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destinationAirport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='airline.Airport'),
        ),
    ]
